#!/bin/bash
mkdir -p "Reference/Encyclopedias"
mkdir -p "Reference/Dictionaries"
mkdir -p "Reference/Thesauruses"
mkdir -p "Reference/Wikipedia"
mkdir -p "Enrichment/Math/Numerical Literacy"
mkdir -p "Enrichment/Math/Operational Skills"
mkdir -p "Enrichment/Mathematics/Algebra"
mkdir -p "Enrichment/Mathematics/Geometry"
mkdir -p "Enrichment/Mathematics/Calculus"
mkdir -p "Enrichment/Mathematics/Statistics"
mkdir -p "Enrichment/Science/Biology"
mkdir -p "Enrichment/Science/Chemistry"
mkdir -p "Enrichment/Science/Physics"
mkdir -p "Enrichment/Science/Life Science"
mkdir -p "Enrichment/Science/Earth Science"
mkdir -p "Enrichment/Science/Space"
mkdir -p "Enrichment/History/World History"
mkdir -p "Enrichment/History/US History"
mkdir -p "Enrichment/History/Cultural Studies"
mkdir -p "Enrichment/English/Reading & Writing Comprehension & Appreciation"
mkdir -p "Enrichment/English/Grammar & Spelling"
mkdir -p "Enrichment/Nutrition"
mkdir -p "Enrichment/Creative Expression/Music Theory & Composition"
mkdir -p "Enrichment/Creative Expression/Arts & Crafts"
mkdir -p "Enrichment/Creative Expression/Theater Arts & Dance"
mkdir -p "Enrichment/Personal Development/Mental Health Awareness"
mkdir -p "Enrichment/Personal Development/Addiction Recovery Resources"
mkdir -p "Enrichment/Personal Development/Self-Sufficiency"
mkdir -p "Enrichment/Language Arts/Reading & Writing"
mkdir -p "Enrichment/Language Arts/Grammar & Spelling"
mkdir -p "Enrichment/Business Skills/Marketing & Advertising"
mkdir -p "Enrichment/Business Skills/Management & Leadership"
mkdir -p "Enrichment/Business Skills/Accounting & Bookkeeping"
mkdir -p "Enrichment/Business Skills/Sales & Customer Service"
mkdir -p "Enrichment/Computer Science/Coding & Programming"
mkdir -p "Enrichment/Computer Science/Software Development & Design"
mkdir -p "Enrichment/Culinary Arts"
mkdir -p "Enrichment/Health Care/Preventative Medicine"
mkdir -p "Enrichment/Health Care/Nutrition & Dietetics"
mkdir -p "Enrichment/Language Studies/English Language Learners (ELL)"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Spanish"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/French"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Italian"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/German"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Portuguese"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Russian"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Japanese"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Arabic"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Chinese"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Danish"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Hindi"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Polish"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Swedish"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Turkish"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Greek"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Dutch"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Hebrew"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Romanian"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Korean"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Norwegian"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Finnish"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Indonesian"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Czech"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Hungarian"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Thai"
mkdir -p "Enrichment/Language Studies/Modern Foreign Language (MFL)/Malay"
mkdir -p "Enrichment/Environmental Studies/Sustainability Practices"
mkdir -p "Enrichment/Environmental Studies/Sustainability Practices/Travel"
mkdir -p "Enrichment/Environmental Studies/Sustainability Practices/Leisure Activities"
mkdir -p "Enrichment/Environmental Studies/Sustainable Agriculture"
mkdir -p "Enrichment/Environmental Studies/Renewable Energy"
mkdir -p "Enrichment/Environmental Studies/Wilderness Survival"
mkdir -p "Enrichment/Environmental Studies/Natural Disaster Preparedness"
mkdir -p "Enrichment/Environmental Studies/Renewable Resource Management"
mkdir -p "Enrichment/Economics/Neoclassical Economics"
mkdir -p "Enrichment/Economics/Marxist Economics"
mkdir -p "Enrichment/Economics/Keynesian Economics"
mkdir -p "Enrichment/Economics/Post Keynesian Economics"
mkdir -p "Enrichment/Economics/Austrian Economics"
mkdir -p "Enrichment/Economics/Behavioral Economics"
mkdir -p "Enrichment/Economics/Feminist Economics"
mkdir -p "Enrichment/Economics/Green Economics"
mkdir -p "Enrichment/Life Skills (e.g. self-care, communication, etc.)/Conflict Resolution and Negotiation"
mkdir -p "Enrichment/Life Skills (e.g. self-care, communication, etc.)/Organizational Strategy and Planning"
mkdir -p "Enrichment/Life Skills (e.g. self-care, communication, etc.)/Critical Thinking & Problem Solving"
mkdir -p "Enrichment/Life Skills (e.g. self-care, communication, etc.)/Interpersonal Relations & Communication"
mkdir -p "Enrichment/Finance/Personal Financial Literacy"
mkdir -p "Enrichment/Finance/Investment Theory & Practice"
mkdir -p "Enrichment/Politics & Government/Political Ideologies & Analysis"
mkdir -p "Enrichment/Politics & Government/Governmental Structures & Policies"
mkdir -p "Enrichment/Community Organization/Volunteering"
mkdir -p "Enrichment/Community Organization/Social Justice"
mkdir -p "Enrichment/Permaculture Practices/Circular Economies"
mkdir -p "Enrichment/Animal Husbandry"
mkdir -p "Enrichment/Building Construction and Repair"
mkdir -p "Enrichment/Carpentry and Woodworking"
mkdir -p "Enrichment/Mechanics and Automotive Repair"
mkdir -p "Enrichment/Herbalism and Holistic Medicine/Emergency First-Aid"
mkdir -p "Enrichment/Psychology"
mkdir -p "Enrichment/Sociology"
mkdir -p "Enrichment/Philosophy"
mkdir -p "Enrichment/Religion"
mkdir -p "Entertainment/Documentaries"
mkdir -p "Entertainment/Games"
mkdir -p "Entertainment/Movies"
mkdir -p "Entertainment/Music"
mkdir -p "Entertainment/TV"
