mkdir -p "Childhood Education/Math/Numerical Literacy"
mkdir -p "Childhood Education/Math/Operational Skills"
mkdir -p "Childhood Education/Math/Algebraic Reasoning & Advanced Math"
mkdir -p "Childhood Education/Science/Life Science"
mkdir -p "Childhood Education/Science/Physical Science"
mkdir -p "Childhood Education/Science/Earth & Space Science"
mkdir -p "Childhood Education/History/World History"
mkdir -p "Childhood Education/History/US History"
mkdir -p "Childhood Education/History/Cultural Studies"
mkdir -p "Childhood Education/Language Arts/Reading & Writing Comprehension & Appreciation"
mkdir -p "Childhood Education/Language Arts/Grammar & Spelling"
mkdir -p "Childhood Education/Nutrition"
mkdir -p "Childhood Education/Creative Expression/Music Theory & Composition"
mkdir -p "Childhood Education/Creative Expression/Arts & Crafts"
mkdir -p "Childhood Education/Creative Expression/Theater Arts & Dance"
mkdir -p "Childhood Education/Personal Development/Mental Health Awareness"
mkdir -p "Childhood Education/Personal Development/Addiction Recovery Resources"
mkdir -p "Childhood Education/Personal Development/Self-Sufficiency"
mkdir -p "Reference Library/Encyclopedias"
mkdir -p "Reference Library/Dictionaries"
mkdir -p "Reference Library/Thesauruses"
mkdir -p "Reference Library/Wikipedia"
mkdir -p "Adult Education & Vocational Mastery/Mathematics & Science/Algebra"
mkdir -p "Adult Education & Vocational Mastery/Mathematics & Science/Geometry"
mkdir -p "Adult Education & Vocational Mastery/Mathematics & Science/Calculus"
mkdir -p "Adult Education & Vocational Mastery/Mathematics & Science/Biology"
mkdir -p "Adult Education & Vocational Mastery/Mathematics & Science/Chemistry"
mkdir -p "Adult Education & Vocational Mastery/Mathematics & Science/Physics"
mkdir -p "Adult Education & Vocational Mastery/Language Arts/Reading & Writing"
mkdir -p "Adult Education & Vocational Mastery/Language Arts/Grammar & Spelling"
mkdir -p "Adult Education & Vocational Mastery/Business Skills/Marketing & Advertising"
mkdir -p "Adult Education & Vocational Mastery/Business Skills/Management & Leadership"
mkdir -p "Adult Education & Vocational Mastery/Business Skills/Accounting & Bookkeeping"
mkdir -p "Adult Education & Vocational Mastery/Business Skills/Sales & Customer Service"
mkdir -p "Adult Education & Vocational Mastery/Computer Science/Coding & Programming"
mkdir -p "Adult Education & Vocational Mastery/Computer Science/Software Development & Design"
mkdir -p "Adult Education & Vocational Mastery/Culinary Arts"
mkdir -p "Adult Education & Vocational Mastery/Health Care/Preventative Medicine"
mkdir -p "Adult Education & Vocational Mastery/Health Care/Nutrition & Dietetics"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/English Language Learners (ELL)"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Spanish"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/French"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Italian"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/German"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Portuguese"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Russian"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Japanese"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Arabic"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Chinese"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Danish"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Hindi"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Polish"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Swedish"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Turkish"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Greek"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Dutch"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Hebrew"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Romanian"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Korean"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Norwegian"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Finnish"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Indonesian"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Czech"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Hungarian"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Thai"
mkdir -p "Adult Education & Vocational Mastery/Language Studies/Modern Foreign Language (MFL)/Malay"
mkdir -p "Entertainment/Games"
mkdir -p "Entertainment/Movies"
mkdir -p "Entertainment/Music"
mkdir -p "Entertainment/TV"
mkdir -p "Personal Enrichment/Psychology"
mkdir -p "Personal Enrichment/Sociology"
mkdir -p "Personal Enrichment/Philosophy"
mkdir -p "Personal Enrichment/Religion"
mkdir -p "Personal Enrichment/Environmental Studies/Sustainability Practices"
mkdir -p "Personal Enrichment/Environmental Studies/Sustainability Practices/Travel"
mkdir -p "Personal Enrichment/Environmental Studies/Sustainability Practices/Leisure Activities"
mkdir -p "Personal Enrichment/Environmental Studies/Sustainable Agriculture"
mkdir -p "Personal Enrichment/Environmental Studies/Renewable Energy"
mkdir -p "Personal Enrichment/Environmental Studies/Wilderness Survival"
mkdir -p "Personal Enrichment/Environmental Studies/Natural Disaster Preparedness"
mkdir -p "Personal Enrichment/Environmental Studies/Renewable Resource Management"
mkdir -p "Personal Enrichment/Economics/Neoclassical Economics"
mkdir -p "Personal Enrichment/Economics/Marxist Economics"
mkdir -p "Personal Enrichment/Life Skills (e.g. self-care, communication, etc.)/Conflict Resolution and Negotiation"
mkdir -p "Personal Enrichment/Life Skills (e.g. self-care, communication, etc.)/Organizational Strategy and Planning"
mkdir -p "Personal Enrichment/Life Skills (e.g. self-care, communication, etc.)/Critical Thinking & Problem Solving"
mkdir -p "Personal Enrichment/Life Skills (e.g. self-care, communication, etc.)/Interpersonal Relations & Communication"
mkdir -p "Personal Enrichment/Finance/Personal Financial Literacy"
mkdir -p "Personal Enrichment/Finance/Investment Theory & Practice"
mkdir -p "Personal Enrichment/Politics & Government/Political Ideologies & Analysis"
mkdir -p "Personal Enrichment/Politics & Government/Governmental Structures & Policies"
mkdir -p "Personal Enrichment/Community Organization/Volunteering"
mkdir -p "Personal Enrichment/Community Organization/Social Justice"
mkdir -p "Personal Enrichment/Permaculture Practices/Circular Economies"
mkdir -p "Personal Enrichment/Animal Husbandry"
mkdir -p "Personal Enrichment/Carpentry and Woodworking"
mkdir -p "Personal Enrichment/Mechanics and Automotive Repair"
mkdir -p "Personal Enrichment/Herbalism and Holistic Medicine/Emergency First-Aid"
